# Recurrent Neural Networks
You should build an end-to-end machine learning pipeline using a recurrent neural network model. In particular, you should do the following:
- Load the `jena climate` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the [keras repository](https://keras.io/examples/timeseries/timeseries_weather_forecasting/).
- Split the dataset into training, validation, and test sets. Note that you cannot split time series using [Scikit-Learn](https://keras.io/examples/timeseries/timeseries_weather_forecasting/).
- Build an end-to-end machine learning pipeline, including a [recurrent neural network](https://keras.io/examples/timeseries/timeseries_weather_forecasting/) model.
- Optimize your pipeline by validating your design decisions.
- Test the best pipeline on the test set and report various [evaluation metrics](https://scikit-learn.org/0.15/modules/model_evaluation.html).  
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [1]:
!wget https://storage.googleapis.com/tensorflow/tf-keras-datasets/jena_climate_2009_2016.csv.zip
!unzip jena_climate_2009_2016.csv.zip

--2025-06-03 12:12:32--  https://storage.googleapis.com/tensorflow/tf-keras-datasets/jena_climate_2009_2016.csv.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.204.207, 172.217.203.207, 142.250.98.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.204.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13568290 (13M) [application/zip]
Saving to: ‘jena_climate_2009_2016.csv.zip.11’

jena_climate_2009_2 100%[===================>]  12.94M  --.-KB/s    in 0.06s

2025-06-03 12:12:32 (199 MB/s) - ‘jena_climate_2009_2016.csv.zip.11’ saved [13568290/13568290]

Archive:  jena_climate_2009_2016.csv.zip
replace jena_climate_2009_2016.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: jena_climate_2009_2016.csv

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
df = pd.read_csv('jena_climate_2009_2016.csv')
df.head()

,Date Time,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
0,01.01.2009 00:10:00,996.52,-8.02,265.40,-8.90,93.3,3.33,3.11,0.22,1.94,3.12,1307.75,1.03,1.75,152.3
1,01.01.2009 00:20:00,996.57,-8.41,265.01,-9.28,93.4,3.23,3.02,0.21,1.89,3.03,1309.80,0.72,1.50,136.1
2,01.01.2009 00:30:00,996.53,-8.51,264.91,-9.31,93.9,3.21,3.01,0.20,1.88,3.02,1310.24,0.19,0.63,171.6
3,01.01.2009 00:40:00,996.51,-8.31,265.12,-9.07,94.2,3.26,3.07,0.19,1.92,3.08,1309.19,0.34,0.50,198.0
4,01.01.2009 00:50:00,996.51,-8.27,265.15,-9.04,94.1,3.27,3.08,0.19,1.92,3.09,1309.00,0.32,0.63,214.3

In [4]:
df.shape

(420551, 15)

In [5]:
df['Date Time'] = pd.to_datetime(df['Date Time'], format='%d.%m.%Y %H:%M:%S')
df_midnight = df[(df['Date Time'].dt.hour == 0) & (df['Date Time'].dt.minute == 0)]

In [6]:
df_train = df_midnight[:int(0.5 * len(df_midnight))]
df_val = df_midnight[int(0.5 * len(df_midnight)):int(0.75 * len(df_midnight))]
df_test = df_midnight[int(0.75 * len(df_midnight)):]

print(f"Dataset size: {df_midnight.shape}")
print(f"Training dataset size: {df_train.shape}")
print(f"Validation dataset size: {df_val.shape}")
print(f"Test dataset size: {df_test.shape}")

Dataset size: (2920, 15)
Training dataset size: (1460, 15)
Validation dataset size: (730, 15)
Test dataset size: (730, 15)

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 143 to 210237
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date Time        1460 non-null   datetime64[ns]
 1   p (mbar)         1460 non-null   float64
 2   T (degC)         1460 non-null   float64
 3   Tpot (K)         1460 non-null   float64
 4   Tdew (degC)      1460 non-null   float64
 5   rh (%)           1460 non-null   float64
 6   VPmax (mbar)     1460 non-null   float64
 7   VPact (mbar)     1460 non-null   float64
 8   VPdef (mbar)     1460 non-null   float64
 9   sh (g/kg)        1460 non-null   float64
 10  H2OC (mmol/mol)  1460 non-null   float64
 11  rho (g/m**3)     1460 non-null   float64
 12  wv (m/s)         1460 non-null   float64
 13  max. wv (m/s)    1460 non-null   float64
 14  wd (deg)         1460 non-null   float64
dtypes: datetime64[ns](1), float64(14)
memory usage: 182.5 KB

In [8]:
df_train.describe()

,Date Time,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
count,1460,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,2010-12-31 20:59:30.410958848,988.994110,7.243548,281.297842,4.209849,81.990760,11.387123,9.122384,2.264705,5.763425,9.226897,1225.392979,1.699493,2.751877,185.089500
min,2009-01-02 00:00:00,952.330000,-21.090000,252.470000,-23.010000,42.750000,1.130000,0.950000,0.000000,0.590000,0.950000,1142.580000,0.000000,0.000000,0.000000
25%,2010-01-01 18:00:00,983.967500,2.045000,276.227500,-0.455000,74.600000,7.077500,5.907500,0.677500,3.750000,6.010000,1197.717500,0.770000,1.400000,163.750000
50%,2010-12-31 12:00:00,989.630000,8.085000,282.190000,4.730000,83.700000,10.800000,8.565000,1.570000,5.430000,8.700000,1220.090000,1.340000,2.250000,204.600000
75%,2011-12-31 06:00:00,994.422500,12.930000,287.100000,9.547500,91.125000,14.930000,11.925000,3.172500,7.505000,12.015000,1248.160000,2.262500,3.520000,234.525000
max,2012-12-30 00:00:00,1011.910000,24.310000,298.150000,18.760000,100.000000,30.450000,21.690000,13.040000,13.770000,21.960000,1381.560000,10.970000,16.140000,359.500000
std,NaN,8.452016,7.637388,7.745210,7.064406,11.294365,5.404897,4.091730,2.149438,2.596520,4.142257,38.164431,1.351278,1.965531,79.473744

In [9]:
x_train = df_train.drop(["T (degC)"], axis=1)
y_train = df_train["T (degC)"]

x_val = df_val.drop(["T (degC)"], axis=1)
y_val = df_val["T (degC)"]

x_test = df_test.drop(["T (degC)"], axis=1)
y_test = df_test["T (degC)"]

print(f"Shape of x_train:- {x_train.shape}")
print(f"Shape of x_test:- {x_test.shape}")
print(f"Shape of x_val:- {x_val.shape}")
print(f"Shape of y_val:- {y_val.shape}")
print(f"Shape of y_train:- {y_train.shape}")
print(f"Shape of y_test:- {y_test.shape}")

Shape of x_train:- (1460, 14)
Shape of x_test:- (730, 14)
Shape of x_val:- (730, 14)
Shape of y_val:- (730,)
Shape of y_train:- (1460,)
Shape of y_test:- (730,)

In [10]:
numerical_attributes = x_train.select_dtypes(include=['float64']).columns

ct = ColumnTransformer([("scaling", MinMaxScaler(), numerical_attributes)])
ct.fit(x_train)

x_train = ct.transform(x_train)
x_val = ct.transform(x_val)
x_test = ct.transform(x_test)

In [11]:
dataset_train = keras.preprocessing.timeseries_dataset_from_array(x_train, y_train, sequence_length=7, sampling_rate=6, batch_size=256)
dataset_val = keras.preprocessing.timeseries_dataset_from_array(x_val, y_val, sequence_length=7, sampling_rate=6, batch_size=256)

In [12]:
early_stop = keras.callbacks.EarlyStopping(monitor='val_mae', patience=10, restore_best_weights=True)

In [13]:
model = keras.Sequential([
    layers.Input(shape=(100, x_train.shape[1],)),
    layers.LSTM(128, return_sequences=True),
    layers.LSTM(64, return_sequences=True),
    layers.LSTM(32),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001), loss="mse", metrics=["mae"])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 100, 128)       │        72,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100, 64)        │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 149,121 (582.50 KB)

 Trainable params: 149,121 (582.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
path_checkpoint = "model_checkpoint.weights.h5"
es_callback = keras.callbacks.EarlyStopping(monitor="val_loss", min_delta=0, patience=10)

modelckpt_callback = keras.callbacks.ModelCheckpoint(
    monitor="val_loss",
    filepath=path_checkpoint,
    verbose=1,
    save_weights_only=True,
    save_best_only=True,
)

history = model.fit(
    dataset_train,
    epochs=100,
    validation_data=dataset_val,
    callbacks=[es_callback, modelckpt_callback],
)

Epoch 1/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 106.7650 - mae: 8.7548
Epoch 1: val_loss improved from inf to 118.89619, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 314ms/step - loss: 108.1492 - mae: 8.8155 - val_loss: 118.8962 - val_mae: 9.3082
Epoch 2/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 102.2689 - mae: 8.5617
Epoch 2: val_loss improved from 118.89619 to 105.53217, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 156ms/step - loss: 103.0807 - mae: 8.5949 - val_loss: 105.5322 - val_mae: 8.7258
Epoch 3/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 90.4992 - mae: 8.0490
Epoch 3: val_loss improved from 105.53217 to 81.86179, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - loss: 90.3832 - mae: 8.0305 - val_loss: 81.8618 - val_mae: 7.6242
Epoch 4/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 72.9775 - mae: 7.2254
Epoch 4: val_loss improved from 81.86179 to 56.75058, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 170ms/step - loss: 72.1270 - mae: 7.1570 - val_loss: 56.7506 - val_mae: 6.3668
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 59.9818 - mae: 6.4592
Epoch 5: val_loss improved from 56.75058 to 46.93383, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 242ms/step - loss: 59.6465 - mae: 6.4272 - val_loss: 46.9338 - val_mae: 5.7019
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 63.0863 - mae: 6.3396
Epoch 6: val_loss did not improve from 46.93383
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 145ms/step - loss: 62.7587 - mae: 6.3191 - val_loss: 47.1919 - val_mae: 5.6528
Epoch 7/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 64.6514 - mae: 6.3547
Epoch 7: val_loss did not improve from 46.93383
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - loss: 63.6995 - mae: 6.3108 - val_loss: 47.1370 - val_mae: 5.7310
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 60.6610 - mae: 6.2884
Epoch 8: val_loss did not improve from 46.93383
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 135ms/step - loss: 60.4310 - mae: 6.2730 - val_loss: 48.6261 - val_mae: 5.8656
Epoch 9/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 59.5550 - mae: 6.3431
Epoch 9: val_loss did not improve from 46.93383
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 131ms/step - loss: 59.1870 - mae: 6.3036 - val_loss: 49.1913 - val_mae: 5.9056
Epoch 10/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 59.1763 - mae: 6.3464
Epoch 10: val_loss did not improve from 46.93383
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 130ms/step - loss: 58.7639 - mae: 6.3011 - val_loss: 48.2308 - val_mae: 5.8420
Epoch 11/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 58.4376 - mae: 6.2847
Epoch 11: val_loss improved from 46.93383 to 45.56989, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 57.8950 - mae: 6.2337 - val_loss: 45.5699 - val_mae: 5.6671
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 52.0998 - mae: 5.9198
Epoch 12: val_loss improved from 45.56989 to 34.91951, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 175ms/step - loss: 51.6784 - mae: 5.8866 - val_loss: 34.9195 - val_mae: 4.8694
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 31.4422 - mae: 4.5598
Epoch 13: val_loss improved from 34.91951 to 18.66595, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 146ms/step - loss: 31.1068 - mae: 4.5245 - val_loss: 18.6659 - val_mae: 3.3869
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 20.1548 - mae: 3.4636
Epoch 14: val_loss improved from 18.66595 to 14.01994, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 154ms/step - loss: 20.0555 - mae: 3.4520 - val_loss: 14.0199 - val_mae: 2.9788
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 17.3400 - mae: 3.1973
Epoch 15: val_loss did not improve from 14.01994
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 140ms/step - loss: 17.4644 - mae: 3.2098 - val_loss: 15.4056 - val_mae: 3.1841
Epoch 16/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 17.6388 - mae: 3.3205
Epoch 16: val_loss improved from 14.01994 to 11.71140, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 182ms/step - loss: 17.6030 - mae: 3.3090 - val_loss: 11.7114 - val_mae: 2.7357
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 13.3501 - mae: 2.7451
Epoch 17: val_loss improved from 11.71140 to 10.76083, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 240ms/step - loss: 13.4003 - mae: 2.7495 - val_loss: 10.7608 - val_mae: 2.5445
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 12.8165 - mae: 2.6672
Epoch 18: val_loss improved from 10.76083 to 9.38991, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 203ms/step - loss: 12.8454 - mae: 2.6733 - val_loss: 9.3899 - val_mae: 2.4154
Epoch 19/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 10.1335 - mae: 2.3794
Epoch 19: val_loss did not improve from 9.38991
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - loss: 10.3092 - mae: 2.4149 - val_loss: 9.4659 - val_mae: 2.4370
Epoch 20/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 9.1735 - mae: 2.3879
Epoch 20: val_loss improved from 9.38991 to 8.01537, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 149ms/step - loss: 9.3634 - mae: 2.4130 - val_loss: 8.0154 - val_mae: 2.2154
Epoch 21/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 7.9773 - mae: 2.1971
Epoch 21: val_loss improved from 8.01537 to 7.62609, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 8.1663 - mae: 2.2269 - val_loss: 7.6261 - val_mae: 2.1420
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 7.6451 - mae: 2.1718
Epoch 22: val_loss improved from 7.62609 to 6.91391, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 151ms/step - loss: 7.7076 - mae: 2.1818 - val_loss: 6.9139 - val_mae: 2.0508
Epoch 23/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 6.7562 - mae: 2.0512
Epoch 23: val_loss improved from 6.91391 to 6.56803, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 145ms/step - loss: 6.8959 - mae: 2.0737 - val_loss: 6.5680 - val_mae: 2.0045
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 6.5707 - mae: 2.0204
Epoch 24: val_loss improved from 6.56803 to 6.27461, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 152ms/step - loss: 6.6181 - mae: 2.0290 - val_loss: 6.2746 - val_mae: 1.9663
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 6.0939 - mae: 1.9532
Epoch 25: val_loss improved from 6.27461 to 5.87957, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 6.1205 - mae: 1.9577 - val_loss: 5.8796 - val_mae: 1.9017
Epoch 26/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 5.5252 - mae: 1.8648
Epoch 26: val_loss improved from 5.87957 to 5.13768, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 150ms/step - loss: 5.5615 - mae: 1.8705 - val_loss: 5.1377 - val_mae: 1.7732
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 4.8216 - mae: 1.7379
Epoch 27: val_loss improved from 5.13768 to 4.37940, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 156ms/step - loss: 4.8364 - mae: 1.7407 - val_loss: 4.3794 - val_mae: 1.6371
Epoch 28/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 4.0695 - mae: 1.5930
Epoch 28: val_loss improved from 4.37940 to 3.50830, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 177ms/step - loss: 4.1274 - mae: 1.6048 - val_loss: 3.5083 - val_mae: 1.4624
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 3.5961 - mae: 1.4826
Epoch 29: val_loss improved from 3.50830 to 3.21859, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 274ms/step - loss: 3.6419 - mae: 1.4928 - val_loss: 3.2186 - val_mae: 1.4335
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 3.6914 - mae: 1.4947
Epoch 30: val_loss did not improve from 3.21859
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 230ms/step - loss: 3.7584 - mae: 1.5110 - val_loss: 3.6523 - val_mae: 1.5610
Epoch 31/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - loss: 3.8038 - mae: 1.5395
Epoch 31: val_loss did not improve from 3.21859
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 156ms/step - loss: 3.9268 - mae: 1.5675 - val_loss: 4.5856 - val_mae: 1.7767
Epoch 32/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 4.0375 - mae: 1.6083
Epoch 32: val_loss did not improve from 3.21859
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - loss: 4.0232 - mae: 1.6006 - val_loss: 4.8236 - val_mae: 1.7925
Epoch 33/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 4.8763 - mae: 1.7173
Epoch 33: val_loss improved from 3.21859 to 2.97291, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - loss: 4.9481 - mae: 1.7253 - val_loss: 2.9729 - val_mae: 1.3792
Epoch 34/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 3.3408 - mae: 1.4377
Epoch 34: val_loss improved from 2.97291 to 2.95850, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 150ms/step - loss: 3.4145 - mae: 1.4546 - val_loss: 2.9585 - val_mae: 1.3456
Epoch 35/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 3.0341 - mae: 1.3793
Epoch 35: val_loss did not improve from 2.95850
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 133ms/step - loss: 3.1098 - mae: 1.4000 - val_loss: 3.3021 - val_mae: 1.4398
Epoch 36/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 3.0141 - mae: 1.4092
Epoch 36: val_loss improved from 2.95850 to 2.19374, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 149ms/step - loss: 3.0096 - mae: 1.4042 - val_loss: 2.1937 - val_mae: 1.1700
Epoch 37/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 2.1264 - mae: 1.1460
Epoch 37: val_loss improved from 2.19374 to 2.00159, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 141ms/step - loss: 2.1869 - mae: 1.1615 - val_loss: 2.0016 - val_mae: 1.1177
Epoch 38/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 1.9744 - mae: 1.0858
Epoch 38: val_loss improved from 2.00159 to 1.85672, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 145ms/step - loss: 2.0541 - mae: 1.1106 - val_loss: 1.8567 - val_mae: 1.0790
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 1.9763 - mae: 1.0938
Epoch 39: val_loss improved from 1.85672 to 1.76979, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 188ms/step - loss: 2.0053 - mae: 1.1017 - val_loss: 1.7698 - val_mae: 1.0659
Epoch 40/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.9283 - mae: 1.0764
Epoch 40: val_loss improved from 1.76979 to 1.64098, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 2.0051 - mae: 1.0969 - val_loss: 1.6410 - val_mae: 1.0293
Epoch 41/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.9318 - mae: 1.0644
Epoch 41: val_loss improved from 1.64098 to 1.61174, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 163ms/step - loss: 2.0096 - mae: 1.0870 - val_loss: 1.6117 - val_mae: 1.0229
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 1.8368 - mae: 1.0466
Epoch 42: val_loss improved from 1.61174 to 1.49848, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 245ms/step - loss: 1.8601 - mae: 1.0535 - val_loss: 1.4985 - val_mae: 0.9881
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 1.6739 - mae: 1.0000
Epoch 43: val_loss improved from 1.49848 to 1.36195, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 224ms/step - loss: 1.6948 - mae: 1.0067 - val_loss: 1.3620 - val_mae: 0.9425
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 1.5159 - mae: 0.9515
Epoch 44: val_loss improved from 1.36195 to 1.28032, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 152ms/step - loss: 1.5345 - mae: 0.9580 - val_loss: 1.2803 - val_mae: 0.9130
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 1.3382 - mae: 0.9030
Epoch 45: val_loss improved from 1.28032 to 1.17334, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 1.3524 - mae: 0.9083 - val_loss: 1.1733 - val_mae: 0.8751
Epoch 46/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 1.1758 - mae: 0.8465
Epoch 46: val_loss improved from 1.17334 to 1.06935, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 143ms/step - loss: 1.2078 - mae: 0.8600 - val_loss: 1.0694 - val_mae: 0.8368
Epoch 47/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.0951 - mae: 0.8125
Epoch 47: val_loss improved from 1.06935 to 0.96799, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 144ms/step - loss: 1.1305 - mae: 0.8287 - val_loss: 0.9680 - val_mae: 0.7958
Epoch 48/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.9969 - mae: 0.7797
Epoch 48: val_loss improved from 0.96799 to 0.86818, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 171ms/step - loss: 1.0416 - mae: 0.8003 - val_loss: 0.8682 - val_mae: 0.7471
Epoch 49/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.8692 - mae: 0.7370
Epoch 49: val_loss did not improve from 0.86818
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 130ms/step - loss: 0.9104 - mae: 0.7556 - val_loss: 0.9039 - val_mae: 0.7586
Epoch 50/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.7940 - mae: 0.7058
Epoch 50: val_loss improved from 0.86818 to 0.74265, saving model to model_checkpoint.weights.h5
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 144ms/step - loss: 0.8181 - mae: 0.7150 - val_loss: 0.7427 - val_mae: 0.6833
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.8132 - mae: 0.6957
Epoch 51: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 162ms/step - loss: 0.8297 - mae: 0.7035 - val_loss: 1.3447 - val_mae: 0.8885
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 1.6163 - mae: 0.9861
Epoch 52: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 133ms/step - loss: 1.6511 - mae: 0.9995 - val_loss: 0.9703 - val_mae: 0.7793
Epoch 53/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1.3867 - mae: 0.9399
Epoch 53: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 155ms/step - loss: 1.4558 - mae: 0.9685 - val_loss: 1.9721 - val_mae: 1.0878
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 2.4339 - mae: 1.1779
Epoch 54: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 195ms/step - loss: 2.4255 - mae: 1.1828 - val_loss: 2.0045 - val_mae: 1.1995
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 1.7741 - mae: 1.0973
Epoch 55: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 219ms/step - loss: 1.7901 - mae: 1.0999 - val_loss: 1.1768 - val_mae: 0.8636
Epoch 56/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 1.4585 - mae: 0.9209
Epoch 56: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - loss: 1.4959 - mae: 0.9343 - val_loss: 1.4608 - val_mae: 1.0107
Epoch 57/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 1.2290 - mae: 0.8885
Epoch 57: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - loss: 1.2300 - mae: 0.8858 - val_loss: 1.4281 - val_mae: 0.9724
Epoch 58/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 1.3068 - mae: 0.9020
Epoch 58: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 135ms/step - loss: 1.3639 - mae: 0.9205 - val_loss: 1.8016 - val_mae: 1.1301
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1.8858 - mae: 1.1265
Epoch 59: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 132ms/step - loss: 1.8973 - mae: 1.1293 - val_loss: 2.9129 - val_mae: 1.5280
Epoch 60/100
5/6 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 2.3437 - mae: 1.3250
Epoch 60: val_loss did not improve from 0.74265
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 133ms/step - loss: 2.3043 - mae: 1.2967 - val_loss: 1.9612 - val_mae: 1.2078